services:
  - type: web
    name: davomat-django
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py ensure_super && python manage.py load_sheet_data && python manage.py set_webhook && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PUBLIC_BASE_URL
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
      - key: TG_BOT_USERNAME
        sync: false
      - key: TG_WEBHOOK_SECRET
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: EXCELLENCE_PASSWORD
        sync: false
      - key: SUPER_MANAGER_PHONE
        sync: false
      - key: SUPER_MANAGER_PASSWORD
        sync: false
      # Build jarayonida `ensure_super` avtomatik ravishda
      # SUPER_MANAGER_PHONE bo'yicha supermenejer yarata oladi.
      # Yangi deploy uchun telefon: 900562345