# Generated by Django 6.0.7 on 2026-07-16 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0002_adchannel_lead_course_source_group_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('single', "Bitta o'quvchi"), ('group', 'Guruh'), ('all', "Barcha o'quvchilar")], default='single', max_length=10)),
                ('text', models.TextField(verbose_name='Matn')),
                ('status', models.CharField(choices=[('sent', 'Yuborildi'), ('failed', 'Xato'), ('no_chat', 'Botga ulanmagan')], default='sent', max_length=10)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='register_withvue.student')),
            ],
            options={
                'verbose_name': 'Yuborilgan xabar',
                'verbose_name_plural': 'Yuborilgan xabarlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Telegram chat ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('tg_name', models.CharField(blank=True, max_length=200, verbose_name='TG ismi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tg_subscribers', to='register_withvue.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Telegram obunachi',
                'verbose_name_plural': 'Telegram obunachilar',
            },
        ),
    ]
