# Generated by Django 6.0.7 on 2026-07-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0004_sheetimportmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Telefon')),
                ('code', models.CharField(max_length=6, verbose_name='Kod')),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0, verbose_name='Urinishlar')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Telefon tasdiqlash',
                'verbose_name_plural': 'Telefon tasdiqlashlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
