# Generated by Django 6.0.7 on 2026-07-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0006_group_needs_review_group_review_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='manual_teacher',
            field=models.BooleanField(default=False, verbose_name="Ustoz qo'lda biriktirilgan"),
        ),
    ]
