# Generated by Django 6.0.7 on 2026-07-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0007_student_manual_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetimportmeta',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='Oxirgi xato'),
        ),
    ]
