# Generated by Django 6.0.7 on 2026-07-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0010_alter_group_schedule_alter_student_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Chegirma'),
        ),
        migrations.AddField(
            model_name='student',
            name='monthly_discount',
            field=models.IntegerField(default=0, verbose_name='Doimiy oylik chegirma'),
        ),
    ]
