# Generated by Django 6.0.7 on 2026-07-27 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0011_payment_discount_student_monthly_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='register_withvue.group'),
        ),
    ]
