# Generated by Django 6.0.7 on 2026-07-27 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0012_lesson_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, max_length=32, verbose_name='Karta raqami')),
                ('card_holder', models.CharField(blank=True, max_length=100, verbose_name='Karta egasi')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "To'lov sozlamasi",
                'verbose_name_plural': "To'lov sozlamalari",
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_b64', models.TextField(blank=True, verbose_name='Chek rasmi (base64)')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='pending', max_length=10)),
                ('amount', models.IntegerField(default=0, verbose_name='Miqdor')),
                ('month', models.CharField(blank=True, max_length=7, verbose_name='Oy (YYYY-MM)')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name="To'langan sana")),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='register_withvue.student')),
            ],
            options={
                'verbose_name': "To'lov so'rovi",
                'verbose_name_plural': "To'lov so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
