# Generated by Django 6.0.7 on 2026-07-31 12:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0013_paymentsettings_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_super',
            field=models.BooleanField(default=False, verbose_name='Supermenejer'),
        ),
        migrations.AddField(
            model_name='manager',
            name='permissions',
            field=models.JSONField(blank=True, default=list, verbose_name='Vakolatlar'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary_per_student',
            field=models.IntegerField(default=0, verbose_name="Bir o'quvchi uchun stavka"),
        ),
        migrations.CreateModel(
            name='TeacherAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, verbose_name='Oy (YYYY-MM)')),
                ('amount', models.IntegerField(default=0, verbose_name='Summa')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_advances', to='register_withvue.expense', verbose_name='Xarajat yozuvi')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='register_withvue.teacher')),
            ],
            options={
                'verbose_name': 'Ustoz avansi',
                'verbose_name_plural': 'Ustoz avanslari',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64, verbose_name='Qurilma ID')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Telefon')),
                ('role', models.CharField(choices=[('manager', 'Menejer'), ('super', 'Supermenejer'), ('teacher', 'Ustoz'), ('student', "O'quvchi")], default='manager', max_length=10)),
                ('user_name', models.CharField(blank=True, max_length=200, verbose_name='Kim')),
                ('user_agent', models.CharField(blank=True, max_length=400, verbose_name='Brauzer')),
                ('ip', models.CharField(blank=True, max_length=64, verbose_name='IP manzil')),
                ('login_count', models.IntegerField(default=0, verbose_name='Kirishlar soni')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Bloklangan')),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='register_withvue.manager')),
            ],
            options={
                'verbose_name': 'Kirgan qurilma',
                'verbose_name_plural': 'Kirgan qurilmalar',
                'ordering': ['-last_seen'],
                'unique_together': {('device_id', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, verbose_name='Oy (YYYY-MM)')),
                ('manual_amount', models.IntegerField(blank=True, null=True, verbose_name="Qo'lda kiritilgan summa")),
                ('students_count', models.IntegerField(default=0, verbose_name="O'quvchilar soni")),
                ('paid_amount', models.IntegerField(default=0, verbose_name="To'langan summa")),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'landi")),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_salaries', to='register_withvue.expense', verbose_name='Xarajat yozuvi')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='register_withvue.teacher')),
            ],
            options={
                'verbose_name': 'Ustoz oyligi',
                'verbose_name_plural': 'Ustoz oyliklari',
                'ordering': ['-month', 'teacher__name'],
                'unique_together': {('teacher', 'month')},
            },
        ),
    ]
