# Generated by Django 6.0.7 on 2026-07-31 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0015_backfill_manager_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('actor_name', models.CharField(blank=True, max_length=200, verbose_name='Kim')),
                ('actor_role', models.CharField(blank=True, max_length=10, verbose_name='Roli')),
                ('action', models.CharField(db_index=True, max_length=50, verbose_name='Amal')),
                ('description', models.CharField(max_length=300, verbose_name='Tavsif')),
                ('target_type', models.CharField(blank=True, max_length=30)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_name', models.CharField(blank=True, max_length=200)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='register_withvue.manager')),
            ],
            options={
                'verbose_name': 'Harakat yozuvi',
                'verbose_name_plural': 'Harakatlar jurnali',
                'ordering': ['-created_at'],
            },
        ),
    ]
