# Generated by Django 6.0.7 on 2026-07-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0016_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='salary_mode',
            field=models.CharField(choices=[('per_student', "O'quvchi soniga qarab"), ('percent', "Yig'ilgan puldan foiz")], default='per_student', max_length=12, verbose_name='Oylik hisoblash usuli'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="Yig'ilgan puldan foiz (%)"),
        ),
    ]
