# Generated by Django 6.0.7 on 2026-08-01 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0017_teacher_salary_mode_teacher_salary_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('serial', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Seriya raqami')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Joyi')),
                ('secret', models.CharField(max_length=64, unique=True, verbose_name='Maxfiy kalit')),
                ('host', models.CharField(blank=True, max_length=200, verbose_name='Terminal manzili (http://ip:port)')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='Login')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='Parol')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('last_event_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi hodisa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Yuz tanish terminali',
                'verbose_name_plural': 'Yuz tanish terminallari',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='face_person_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='Terminaldagi raqami'),
        ),
        migrations.CreateModel(
            name='FaceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(db_index=True, max_length=32, verbose_name='Terminaldagi raqam')),
                ('person_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('marked', 'Davomat belgilandi'), ('already', 'Allaqachon belgilangan'), ('no_lesson', "Bugun dars yo'q"), ('no_group', 'Guruhga biriktirilmagan'), ('unknown', "O'quvchi topilmadi"), ('ignored', "E'tiborsiz qoldirildi")], default='unknown', max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('happened_at', models.DateTimeField(verbose_name='Terminal vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_events', to='register_withvue.attendance')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='register_withvue.facedevice')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_events', to='register_withvue.student')),
            ],
            options={
                'verbose_name': 'Yuz tanish hodisasi',
                'verbose_name_plural': 'Yuz tanish hodisalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
