# Generated by Django 6.0.7 on 2026-08-01 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0018_facedevice_student_face_person_id_faceevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsubscriber',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tg_subscribers', to='register_withvue.lead', verbose_name='Lead'),
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tg_subscribers', to='register_withvue.manager', verbose_name='Menejer'),
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='role',
            field=models.CharField(choices=[('student', "O'quvchi"), ('teacher', 'Ustoz'), ('manager', 'Menejer'), ('lead', 'Potensial mijoz'), ('unknown', 'Bazada topilmadi')], db_index=True, default='unknown', max_length=10, verbose_name='Roli'),
        ),
        migrations.AddField(
            model_name='telegramsubscriber',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tg_subscribers', to='register_withvue.teacher', verbose_name='Ustoz'),
        ),
    ]
