# Generated by Django 6.0.7 on 2026-08-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0019_telegramsubscriber_lead_telegramsubscriber_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Chek yuborilsinmi')),
                ('template', models.TextField(default="🧾 <b>To'lov cheki</b>\n\nHurmatli {ism}!\n{oy} oyi uchun to'lovingiz qabul qilindi.\n\nTo'langan: <b>{summa}</b>\nOylik to'lov: {jami}\nQolgan: {qolgan}\nSana: {sana}\n\nRahmat! 🙏\n{markaz}", verbose_name='Chek matni')),
                ('center_name', models.CharField(default="ITLINE o'quv markazi", max_length=100, verbose_name='Markaz nomi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chek sozlamasi',
                'verbose_name_plural': 'Chek sozlamalari',
            },
        ),
    ]
