# Generated by Django 6.0.7 on 2026-08-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0020_receiptsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptsettings',
            name='template',
            field=models.TextField(default="🧾 <b>TO'LOV CHEKI</b>\n<code>━━━━━━━━━━━━━━━━━━━━</code>\n👤 <b>{ism}</b>\n👥 Guruh: {guruh}\n📅 Davr: {oy}\n<code>━━━━━━━━━━━━━━━━━━━━</code>\nTo'landi\n   💵 <b>{summa}</b>\nOylik to'lov\n   <code>{jami}</code>\nQolgan qarz\n   <code>{qolgan}</code>\n<code>━━━━━━━━━━━━━━━━━━━━</code>\n✅ <b>To'lov qabul qilindi</b>\n🗓 {sana}\n\nRahmat! 🙏\n<i>{markaz}</i>", verbose_name='Chek matni'),
        ),
    ]
