# Generated by Django 6.0.7 on 2026-08-02 17:37

import django.db.models.deletion
from django.db import migrations, models


def clear_duplicate_person_ids(apps, schema_editor):
    """Takrorlangan terminal raqamlarini bo'shatadi.

    Raqam shu migratsiyagacha unikal emas edi — panelda qo'lda kiritilgan
    bir xil raqamlar bo'lishi mumkin. Ular qolsa `AddConstraint`
    deploy paytida yiqilardi. Har raqamdan eng eskisi (birinchi
    biriktirilgani) qoladi, qolganlari bo'shatiladi — supermenejer
    panelda «Bog'lanmagan» ro'yxatida ko'rib qayta biriktiradi.
    """
    Student = apps.get_model("register_withvue", "Student")

    seen = set()
    duplicates = []
    rows = Student.objects.exclude(face_person_id="").order_by("id").values_list(
        "id", "face_person_id"
    )
    for pk, person_id in rows:
        if person_id in seen:
            duplicates.append(pk)
        else:
            seen.add(person_id)

    if duplicates:
        Student.objects.filter(id__in=duplicates).update(face_person_id="")


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0024_clear_graduate_phones'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_at', models.DateTimeField(blank=True, null=True, verbose_name='Yozilgan rasm sanasi')),
                ('ok', models.BooleanField(default=True, verbose_name='Muvaffaqiyatli')),
                ('error', models.CharField(blank=True, max_length=255, verbose_name='Xato')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Yozilgan vaqt')),
            ],
            options={
                'verbose_name': 'Terminalga yozilgan yuz',
                'verbose_name_plural': 'Terminalga yozilgan yuzlar',
                'ordering': ['-synced_at'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='face_note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Yuz izohi'),
        ),
        migrations.AddField(
            model_name='student',
            name='face_photo',
            field=models.TextField(blank=True, default='', verbose_name='Yuz rasmi (base64 JPEG)'),
        ),
        migrations.AddField(
            model_name='student',
            name='face_status',
            field=models.CharField(choices=[('none', 'Rasm yuborilmagan'), ('pending', 'Terminalga yozilishi kutilmoqda'), ('synced', 'Terminalga yozilgan'), ('rejected', 'Rad etilgan')], db_index=True, default='none', max_length=10, verbose_name='Yuz holati'),
        ),
        migrations.AddField(
            model_name='student',
            name='face_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rasm yangilangan'),
        ),
        migrations.RunPython(
            clear_duplicate_person_ids, migrations.RunPython.noop
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('face_person_id', ''), _negated=True), fields=('face_person_id',), name='uniq_face_person_id'),
        ),
        migrations.AddField(
            model_name='facesync',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syncs', to='register_withvue.facedevice'),
        ),
        migrations.AddField(
            model_name='facesync',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_syncs', to='register_withvue.student'),
        ),
        migrations.AlterUniqueTogether(
            name='facesync',
            unique_together={('device', 'student')},
        ),
    ]
