# Generated by Django 6.0.7 on 2026-08-06 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0025_facesync_student_face_note_student_face_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegisterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Kunlik kassa yoqilgan')),
                ('require_counted', models.BooleanField(default=True, verbose_name='Fizik sanoq majburiy')),
                ('lock_after_close', models.BooleanField(default=True, verbose_name='Topshirilgan smena qulflanadi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kassa sozlamasi',
                'verbose_name_plural': 'Kassa sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashier_name', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Sana')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('closed', 'Topshirilgan')], db_index=True, default='open', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('expected_total', models.IntegerField(default=0, verbose_name='Tizim hisobi')),
                ('counted_total', models.IntegerField(blank=True, null=True, verbose_name='Sanalgan pul')),
                ('difference', models.IntegerField(default=0, verbose_name='Farq')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_sessions', to='register_withvue.manager', verbose_name='Kassir')),
            ],
            options={
                'verbose_name': 'Kassa smenasi',
                'verbose_name_plural': 'Kassa smenalari',
                'ordering': ['-date', '-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=200)),
                ('cashier_name', models.CharField(blank=True, max_length=200)),
                ('amount', models.IntegerField(verbose_name='Summa (ishorali)')),
                ('month', models.CharField(blank=True, max_length=7, verbose_name="To'lov davri")),
                ('kind', models.CharField(choices=[('payment', "To'lov"), ('adjust', 'Tuzatish')], default='payment', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to='register_withvue.manager')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to='register_withvue.payment')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to='register_withvue.student')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='register_withvue.cashsession')),
            ],
            options={
                'verbose_name': 'Kassa yozuvi',
                'verbose_name_plural': 'Kassa yozuvlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
