# Generated by Django 6.0.7 on 2026-08-13 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0026_cashregistersettings_cashsession_cashentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token xeshi')),
                ('role', models.CharField(choices=[('student', "O'quvchi"), ('teacher', 'Ustoz'), ('manager', 'Menejer')], max_length=10)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('device_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_tokens', to='register_withvue.logindevice')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='register_withvue.manager')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='register_withvue.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='register_withvue.teacher')),
            ],
            options={
                'verbose_name': 'Kirish tokeni',
                'verbose_name_plural': 'Kirish tokenlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
