# Generated by Django 6.0.7 on 2026-07-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Kanal (@username)')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Nomi')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('source', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reklama kanali',
                'verbose_name_plural': 'Reklama kanallari',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('phone2', models.CharField(blank=True, max_length=50, verbose_name="Qo'shimcha telefon")),
                ('status', models.CharField(blank=True, max_length=200, verbose_name='Holat')),
                ('interest', models.CharField(blank=True, max_length=200, verbose_name='Qiziqish / Kurs')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('source_sheet', models.CharField(blank=True, max_length=100, verbose_name='Manba varaq')),
                ('source', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead (potensial mijoz)',
                'verbose_name_plural': 'Leadlar',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='source',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='group',
            name='source',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='source',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='is_graduate',
            field=models.BooleanField(default=False, verbose_name='Bitiruvchi'),
        ),
        migrations.AddField(
            model_name='student',
            name='note',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone2',
            field=models.CharField(blank=True, max_length=50, verbose_name="Qo'shimcha telefon"),
        ),
        migrations.AddField(
            model_name='student',
            name='source',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='teacher',
            name='source',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
