# Generated by Django 6.0.7 on 2026-07-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0003_sentmessage_telegramsubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetImportMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='', max_length=20)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sheet import holati',
                'verbose_name_plural': 'Sheet import holati',
            },
        ),
    ]
