# Generated by Django 6.0.7 on 2026-07-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0005_phoneverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='needs_review',
            field=models.BooleanField(default=False, verbose_name='Tekshirish kerak'),
        ),
        migrations.AddField(
            model_name='group',
            name='review_note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nima aniq emas'),
        ),
    ]
