# Generated by Django 6.0.7 on 2026-07-23 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0008_sheetimportmeta_last_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecoinsettings',
            name='payment_grace_days',
            field=models.IntegerField(default=5, verbose_name='Kechikishga ruxsat (kun)'),
        ),
        migrations.AddField(
            model_name='attendancecoinsettings',
            name='payment_ontime',
            field=models.IntegerField(default=120, verbose_name="Vaqtida to'lov uchun coin"),
        ),
        migrations.AddField(
            model_name='group',
            name='opened_date',
            field=models.DateField(blank=True, null=True, verbose_name='Guruh ochilgan sana'),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='reason',
            field=models.CharField(choices=[('exam_pass', "Imtihondan o'tdi"), ('homework_done', 'Vazifa qilingan'), ('homework_partial', 'Vazifa chala qilingan'), ('homework_missed', 'Vazifa qilinmagan'), ('present', 'Darsga keldi'), ('late', 'Kech keldi'), ('absent', 'Darsga kelmadi'), ('manual', "Teacher tomonidan qo'lda"), ('purchase', 'Magazindan xarid'), ('purchase_cancel', 'Xarid bekor qilindi (qaytarildi)'), ('payment_ontime', "Oylik to'lov vaqtida")], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='LessonReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('sent', models.IntegerField(default=0, verbose_name='Yuborildi')),
                ('no_chat', models.IntegerField(default=0, verbose_name='Botga ulanmagan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='register_withvue.group')),
            ],
            options={
                'verbose_name': 'Dars eslatmasi',
                'verbose_name_plural': 'Dars eslatmalari',
                'unique_together': {('group', 'date')},
            },
        ),
    ]
