# Generated by Django 6.0.7 on 2026-07-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0009_attendancecoinsettings_payment_grace_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='schedule',
            field=models.CharField(choices=[('odd', 'Du-Chor-Juma'), ('even', 'Se-Pay-Shan'), ('daily', 'Har kuni')], default='odd', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='schedule',
            field=models.CharField(choices=[('odd', 'Du-Chor-Juma'), ('even', 'Se-Pay-Shan'), ('daily', 'Har kuni')], default='odd', max_length=10),
        ),
    ]
